name: deploy
on:
  push:
    branches: [main]
# give the Action rights to write the Pages branch:
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
     env:                         
      VITE_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - run: pnpm install && pnpm run build

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages        # Ziel-Branch
          folder: dist            # Build-Output-Verzeichnis
